#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

function ensureAnsible() {
  ###################
  # Install ansible #
  if ! grep -q "ansible/ansible" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
      echo "Adding Ansible PPA"
      sudo apt-add-repository ppa:ansible/ansible -y
  fi

  if ! hash ansible >/dev/null 2>&1; then
      echo "Installing Ansible..."
      sudo apt-get update
      sudo apt-get install software-properties-common ansible git python3-apt -y
  else
      echo "Ansible already installed"
  fi
}

if which python3 >/dev/null 2>&1; then
  PYTHON=$(which python3)
else
  PYTHON=$(which python)
fi

echo "                                     ./////,                    "
echo "                                 ./////==//////*                "
echo "                                ////.  ___   ////.              "
echo "                         ,**,. ////  ,////A,  */// ,**,.        "
echo "                    ,/////////////*  */////*  *////////////A    "
echo "                   ////'        \VA.   '|'   .///'       '///*  "
echo "                  *///  .*///*,         |         .*//*,   ///* "
echo "                  (///  (//////)**--_./////_----*//////)   ///) "
echo "                   V///   '°°°°      (/////)      °°°°'   ////  "
echo "                    V/////(////////\. '°°°' ./////////(///(/'   "
echo "                       'V/(/////////////////////////////V'      "

ensureAnsible

BASEDIR=$(dirname "$0")
#####################################
# Display real installation process #
echo ""
echo "Customize the playbook: playbook.yml to suit your needs, then continue by typing the BECOME password:"
echo ""

ansible-playbook ${BASEDIR}/playbook.yml -e @${BASEDIR}/vars.yml -e ansible_python_interpreter=${PYTHON} -c local -i localhost -K
