- name: Get installed version
  shell: pacman -Q --info hashicorp-vagrant | grep Version | awk -F':' '{print $NF}' | awk -F'-' '{print $1}'
  register: vagrant
  changed_when: False

- name: Download vagrant package
  get_url:
    url: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.tar.xz
    dest: /tmp/vagrant_{{ vagrant_version }}_x86_64.tar.xz
  when: vagrant.stdout | trim != vagrant_version
  
- name: Install vagrant
  become: yes
  # code below should work, but it does not
  # pacman:
  #   name: /tmp/vagrant_{{ vagrant_version }}_x86_64.tar.xz
  #   state: present
  shell: pacman -U --noconfirm /tmp/vagrant_{{ vagrant_version }}_x86_64.tar.xz
  when: vagrant.stdout | trim != vagrant_version

- name: Remove downloaded package
  file:
    path: /tmp/vagrant_{{ vagrant_version }}_x86_64.tar.xz
    state: absent
