- name: Get installed version
  shell: dpkg -s vagrant | grep Version | awk -F':' '{print $3}'
  register: vagrant
  changed_when: False

- name: Install vagrant
  become: yes
  apt:
    deb: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb
  when: vagrant.stdout != vagrant_version
