- name: Install screen recording packages
  become: true
  apt:
    name:
    # gif image optimization
    - gifsicle 
    # gif screen recording
    - peek
    # video screen recording
    - kazam
    state: latest
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"
