- name: Check if npm is installed
  shell: which npm
  register: npm
  failed_when: False
  changed_when: False

# beautiful gif terminal recording
- name: Install terminalizer
  become: true
  npm:
    name: terminalizer
    global: yes
    unsafe_perm: yes
  when: npm.rc == 0

- name: Install screen recording packages
  become: true
  apt:
    name:
    # gif image optimization
    - gifsicle 
    # gif screen recording
    - peek
    # video screen recording
    - kazam
    state: latest
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"
