- name: Remove old snap installation (Ubuntu)
  become: yes
  snap:
    name: code
    state: absent

- name: Install vscode gpg key (Ubuntu)
  become: yes
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: Install vscode apt repository (Ubuntu)
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

- name: Install vscode package (Ubuntu)
  become: yes
  apt:
    name: code

- name: install vscode extensions
  command: "code --install-extension '{{ item }}'"
  with_items:
    - esbenp.prettier-vscode
    - k--kato.intellij-idea-keybindings
    - jebbs.plantuml
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"
