- name: Remove old snap installation (Ubuntu)
  become: true
  snap:
    name: code
    state: absent

- name: Install vscode gpg key (Ubuntu)
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: Install vscode apt repository (Ubuntu)
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

- name: Install vscode package (Ubuntu)
  become: true
  apt:
    name: code

- name: install vscode extensions
  command: "code --install-extension '{{ item }}'"
  with_items:
    - esbenp.prettier-vscode
    - k--kato.intellij-idea-keybindings
    - jebbs.plantuml
    - chadalen.vscode-jetbrains-icon-theme
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"

- name: copy vscode settings
  become: true
  become_user: "{{ user }}"
  copy:
    src: settings.json
    dest: "{{ ansible_env.HOME }}/.config/Code/User/settings.json"
  when: chrome.bookmarks
