- name: Check if snap is installed
  stat:
    path: "/usr/bin/snap"
  register: "snap_check"

- name: Remove old snap installation
  become: true
  snap:
    name: code
    state: absent
  when: snap_check.stat.exists

- name: Install vscode gpg key
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: Install vscode apt repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

- name: Install vscode package
  become: true
  apt:
    name: code
    state: latest
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"

- name: install vscode extensions
  command: "code --install-extension '{{ item }}'"
  with_items:
    - esbenp.prettier-vscode
    - k--kato.intellij-idea-keybindings
    - jebbs.plantuml
    - chadalen.vscode-jetbrains-icon-theme
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"

- name: copy vscode settings
  become: true
  become_user: "{{ user }}"
  copy:
    src: settings.json
    dest: "{{ ansible_env.HOME }}/.config/Code/User/settings.json"
  when: chrome.bookmarks
