- name: Capture gcloud version
  shell: gcloud --version | grep "Google Cloud SDK" | sed "s|Google Cloud SDK ||g"
  register: gcloud_capture
  failed_when: false
  args:
    executable:  /usr/bin/bash

- name: Download gcloud archive
  unarchive:
    src: "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-{{ gcloud_tools_version }}-linux-x86_64.tar.gz"
    dest: ~/.local
    remote_src: yes
  when: gcloud_tools_version != gcloud_capture.stdout

- name: Add gcloud rc configs (zshrc)
  lineinfile:
    path: ~/.zshrc
    line: |
      
      # The next line updates PATH for the Google Cloud SDK.
      if [ -f "$HOME/.local/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/.local/google-cloud-sdk/path.zsh.inc"; fi
      
      # The next line enables shell command completion for gcloud.
      if [ -f "$HOME/.local/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/.local/google-cloud-sdk/completion.zsh.inc"; fi
    state: present
    insertafter: EOF
    create: True

- name: Add gcloud rc configs (bash)
  lineinfile:
    path: ~/.bashrc
    line: |
      
      # The next line updates PATH for the Google Cloud SDK.
      if [ -f "$HOME/.local/google-cloud-sdk/path.bash.inc" ]; then . "$HOME/.local/google-cloud-sdk/path.bash.inc"; fi
      
      # The next line enables shell command completion for gcloud.
      if [ -f "$HOME/.local/google-cloud-sdk/completion.bash.inc" ]; then . "$HOME/.local/google-cloud-sdk/completion.bash.inc"; fi
    state: present
    insertafter: EOF
    create: True

