- name: Install gcloud
  include_tasks: gcloud_ubuntu.yml

- name: Install kubectl
  shell: source ~/.local/google-cloud-sdk/path.bash.inc && gcloud components install kubectl --quiet
  args:
    executable:  /usr/bin/bash

- name: Install gke-gcloud-auth-plugin
  shell: source ~/.local/google-cloud-sdk/path.bash.inc && gcloud components install gke-gcloud-auth-plugin
  args:
    executable:  /usr/bin/bash

- name: Install kubectx
  include_tasks: kubectx.yml

- name: Install k9s
  include_tasks: k9s.yml
