- name: Create fonts directory
  file:
    path: ~/.fonts
    state: directory

- name: Download
  get_url:
    url: "{{ item }}"
    dest: ~/.fonts
  with_items:
    - "https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/MesloLGS%20NF%20Regular.ttf"
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
  register: fonts

- name: Rebuild font cache
  shell: fc-cache -f -v
  when: fonts.changed

- name: Capture default terminal profile
  shell: gsettings get org.gnome.Terminal.ProfilesList default | sed "s/'//g"
  register: profile
  changed_when: False
  when: fonts.changed

- name: Set nerd-font for current terminal profile
  shell: gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ profile.stdout }}/" font "MesloLGS NF 11"
  when: fonts.changed

- name: Set use system font to false for current terminal profile
  shell: gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ profile.stdout }}/" use-system-font false
  when: fonts.changed
