- name: Clone fzf repository
  git:
    repo: https://github.com/junegunn/fzf
    dest: ~/.fzf
    update: no

- name: Install fzf
  shell: ~/.fzf/install --no-update-rc
  args:
    creates: ~/.fzf.zsh