- name: Install zsh and required dependencies
  become: true
  apt:
    name:
    - zsh
    - python3
    - python3-pip

- name: Install fzf
  include_tasks: fzf.yml

- name: Install fonts
  include_tasks: font.yml

- name: Install zsh
  include_tasks: zsh.yml
