- name: Install Jabba
  shell: export JABBA_VERSION={{ jabaa_version }} && curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh

- name: Install OpenJDK 8
  become: true
  become_user: "{{ user }}"
  shell: source "{{ ansible_env.HOME }}/.jabba/jabba.sh" && jabba install zulu@1.8.282
  args:
    executable:  /usr/bin/bash

- name: Install OpenJDK 11
  become: true
  become_user: "{{ user }}"
  shell: source "{{ ansible_env.HOME }}/.jabba/jabba.sh" && jabba install zulu@1.11.0-10
  args:
    executable:  /usr/bin/bash

- name: Set OpenJDK 11 as default
  become: true
  become_user: "{{ user }}"
  shell: source "{{ ansible_env.HOME }}/.jabba/jabba.sh" && jabba alias default zulu@1.11.0-10
  args:
    executable:  /usr/bin/bash

- name: Add java aliases
  become: true
  become_user: "{{ user }}"
  lineinfile: 
    path: "{{ ansible_env.HOME }}/.aliases_devbox"
    line: '{{ item }}'
    regexp: '^{{ item }}$'
    state: present
    insertafter: EOF
    create: True
  with_items:
    - alias java8="jabba alias default zulu@1.8.282 && zsh"
    - alias java11="jabba alias default zulu@1.11.0-10 && zsh"
