- name: Check existing mok key
  become: true
  shell: mokutil --test-key /mok/CES_MOCK.der || true
  register: mokutil_test

- name: Create mok directory for a self created mok key
  become: true
  file:
    path: /mok
    state: directory
  when: mokutil_test.stdout != "/mok/CES_MOCK.der is already enrolled"

- name: Create key for signing modules for virtualbox and vmware player
  become: true
  shell: openssl req -new -x509 -newkey rsa:2048 -keyout /mok/CES_MOCK.priv -outform DER -out /mok/CES_MOCK.der -nodes -days 36500 -subj "/CN=Cloudogu EcoSystem/"
  when: mokutil_test.stdout != "/mok/CES_MOCK.der is already enrolled"