- name: Install vagrant package
  become: true
  apt:
    name: vagrant
    state: latest
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"

- name: Install vagrant-disksize plugin
  shell: vagrant plugin install vagrant-disksize
