- name: Check existing mok key
  become: true
  shell: mokutil --test-key /mok/CES_MOCK.der
  register: mokutil_test

- name: Create mok directory for a self created mok key
  become: true
  file:
    path: /mok
    state: directory
  when: mokutil_test.stdout != "/mok/CES_MOCK.der is enrolled"

- name: Create key for signing modules for virtualbox and vmware player
  become: true
  shell: openssl req -new -x509 -newkey rsa:2048 -keyout /mok/CES_MOCK.priv -outform DER -out /mok/CES_MOCK.der -nodes -days 36500 -subj "/CN=Cloudogu EcoSystem/"
  when: mokutil_test.stdout != "/mok/CES_MOCK.der is enrolled"

- name: Prepare input for mok enrollment
  become: true
  expect:
    command: mokutil --import /mok/CES_MOCK.der
    responses:
      (?i)password: "{{ mokutils.password}}"
      (?i)password again: "{{ mokutils.password}}"
  when: mokutil_test.stdout != "/mok/CES_MOCK.der is enrolled"