- name: Install git related tools
  become: true
  apt:
    name: 
    - git
    - git-crypt
    state: latest
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"
  when: ansible_distribution == "Ubuntu"

- name: Check gh client version
  shell: gh --version | head -1 | awk '{print $3}'
  register: gh
  changed_when: False
  when: ansible_distribution == "Ubuntu"

- name: Install GitHub Client
  become: true
  apt:
    deb: https://github.com/cli/cli/releases/download/v{{ gh_version }}/gh_{{ gh_version }}_linux_amd64.deb
  when: ansible_distribution == "Ubuntu" and gh.stdout != gh_version

- name: Check if diff-so-fancy is installed
  stat:
    path: /usr/local/bin/diff-so-fancy
  register: diffsofancy

- name: Render git configuration
  template:
    src: "{{ playbook_dir }}/config/gitconfig.j2"
    dest: ~/.gitconfig
    mode: 0600


