# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="/snap/bin:${PATH}"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=${ZSH_THEME:=powerlevel10k/powerlevel10k}
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs time)
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="▶ "
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY="Default"
COMPLETION_WAITING_DOTS="true"
plugins=(
  # zsh
  zsh-autosuggestions
  zsh-syntax-highlighting

  # scm
  git
  git-flow
  mercurial
  svn
  scm

  # javascript
  npm
  yarn
  gulp

  # golang
  golang

  # java
  mvn
  gradle

  # containers
  docker
  docker-compose
  kubectl

  # virtual machines
  vagrant

  # utils
  wd
  safe-paste
)

# Enable automatic completion bash for gopass
#source <(gopass completion bash)
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src

# load java-env plugin, if is installed
[ -d ~/.oh-my-zsh/custom/plugins/java-env ] && plugins+=(java-env)

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# User configuration
#Setup history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# Freeze
freeze_history () {
    fc -A
    fc -p $HISTFILE
    unset HISTFILE
}

unfreeze_history () {
    fc -P
}

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='nano'

# Set personal aliases, overriding those provided by oh-my-zsh libs.
[ -f ~/.bash_aliases ] && source ~/.bash_aliases
[ -f ~/.kubectl_aliases ] && source ~/.kubectl_aliases
[ -f ~/.docker_aliases ] && source ~/.docker_aliases

# fzf
# add support for ctrl+o to open selected file in VS Code
export FZF_DEFAULT_OPTS="--bind='ctrl-o:execute(code {})+abort'"

# enable gpg ssh agent
[ -f ~/.gnupg/gpgrc ] && source ~/.gnupg/gpgrc

# read fzf configuration, if available
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# configure go dev environment
[ -f ~/.gorc ] && source ~/.gorc

# Configuration for jabba, gvm, nvm
[ -s "/home/jsprey/.jabba/jabba.sh" ] && source "/home/jsprey/.jabba/jabba.sh"
[[ -s "/home/jsprey/.gvm/scripts/gvm" ]] && source "/home/jsprey/.gvm/scripts/gvm"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion