- name: Install cli tools from repository (Ubuntu)
  become: true
  apt:
    name:
      - htop
      - iftop
      - make
      - openssl
      - wget
      - curl
      - subversion
      - jq
      - ncdu
      - btrfs-progs

- name: Install bat
  include_tasks: bat.yml

- name: Install gotop
  include_tasks: gotop.yml

- name: Install ctop
  include_tasks: ctop.yml

- name: Install gopass
  include_tasks: gopass.yml

- name: Install yq
  include_tasks: yq.yml

- name: Install lsd
  include_tasks: lsd.yml

- name: Install pet snippet manager
  include_tasks: pet.yml

- name: Install aliases
  include_tasks: aliases.yml
